name: C++/C# Build

on: [ push, pull_request ]

jobs:
  build-c++:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Boost
      run: sudo apt install libboost-program-options-dev

    - name: CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Install
      run: sudo cmake --install build

  build-c#:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
